version: '3'

networks:
    app-tier:
        driver: bridge
services:
  server:
    build: 
      context: ./server
      dockerfile: DockerFile
    networks:
        - app-tier
    depends_on:
        - rabbitmq
    restart: on-failure
  c1:
    build: 
      context: ./cliente
      dockerfile: DockerFile
    networks:
        - app-tier
    restart: on-failure
    depends_on:
      [server,rabbitmq]
  c1:
    build: 
      context: ./cliente2
      dockerfile: DockerFile
    networks:
        - app-tier
    restart: on-failure
    depends_on:
      [server,rabbitmq]

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: rabbitmq
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    networks:
        - app-tier

