# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListaClientes = channel.unary_stream(
        '/asynch.ChatServer/ListaClientes',
        request_serializer=chat__pb2.MensajeVacio.SerializeToString,
        response_deserializer=chat__pb2.Cliente.FromString,
        )
    self.ObtenerMensajes = channel.unary_stream(
        '/asynch.ChatServer/ObtenerMensajes',
        request_serializer=chat__pb2.Cliente.SerializeToString,
        response_deserializer=chat__pb2.Mensaje.FromString,
        )
    self.EnviarMensaje = channel.unary_unary(
        '/asynch.ChatServer/EnviarMensaje',
        request_serializer=chat__pb2.Mensaje.SerializeToString,
        response_deserializer=chat__pb2.MensajeRecibido.FromString,
        )
    self.Chat = channel.unary_stream(
        '/asynch.ChatServer/Chat',
        request_serializer=chat__pb2.Cliente.SerializeToString,
        response_deserializer=chat__pb2.Mensaje.FromString,
        )
    self.Login = channel.unary_unary(
        '/asynch.ChatServer/Login',
        request_serializer=chat__pb2.Registro.SerializeToString,
        response_deserializer=chat__pb2.RegistroRespuesta.FromString,
        )


class ChatServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListaClientes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ObtenerMensajes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnviarMensaje(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Chat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListaClientes': grpc.unary_stream_rpc_method_handler(
          servicer.ListaClientes,
          request_deserializer=chat__pb2.MensajeVacio.FromString,
          response_serializer=chat__pb2.Cliente.SerializeToString,
      ),
      'ObtenerMensajes': grpc.unary_stream_rpc_method_handler(
          servicer.ObtenerMensajes,
          request_deserializer=chat__pb2.Cliente.FromString,
          response_serializer=chat__pb2.Mensaje.SerializeToString,
      ),
      'EnviarMensaje': grpc.unary_unary_rpc_method_handler(
          servicer.EnviarMensaje,
          request_deserializer=chat__pb2.Mensaje.FromString,
          response_serializer=chat__pb2.MensajeRecibido.SerializeToString,
      ),
      'Chat': grpc.unary_stream_rpc_method_handler(
          servicer.Chat,
          request_deserializer=chat__pb2.Cliente.FromString,
          response_serializer=chat__pb2.Mensaje.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=chat__pb2.Registro.FromString,
          response_serializer=chat__pb2.RegistroRespuesta.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'asynch.ChatServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
